version: '3.7'

services:
  api:
    build: docker/api
    volumes:
      - ./data:/app/data:cached
    ports:
      - 3000:3000
  app:
    build: docker/app
    volumes:
      - ./:/app:cached
    ports:
      - 8080:8080
